insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (1, 'acardwell0', 'Ameline', 'Cardwell', '2005-05-04', 'kL8@_@TI3md\m', '05/26/2003');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (2, 'jfincham1', 'Jacqui', 'Fincham', '1995-03-26', 'sD1|V&C=', '07/26/2000');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (3, 'jduffy2', 'Joyan', 'Duffy', '2007-01-28', 'kN8?~uZ3t', '01/28/2006');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (4, 'mlambkin3', 'Magnum', 'Lambkin', '1994-07-08', 'kV0+LMM8HBP%aS', '09/25/2009');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (5, 'myarker4', 'Minnaminnie', 'Yarker', '1991-02-23', 'wX2.`&L#%', '11/06/2007');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (6, 'pnorthall5', 'Priscilla', 'Northall', '1998-01-13', 'dL5*|<xjd*sO@>P%', '05/04/2007');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (7, 'grushworth6', 'Gerry', 'Rushworth', '1986-09-20', 'zX9%3K76c', '09/23/2007');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (8, 'eingray7', 'Elle', 'Ingray', '2008-04-27', 'qV9`#?g3xV,?\', '08/02/2001');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (9, 'gbrisland8', 'Grace', 'Brisland', '1991-11-17', 'mP7&V}y33', '11/22/2002');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (10, 'vbanker9', 'Violante', 'Banker', '1990-05-04', 'aO6>=<3''?6', '06/02/2002');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (11, 'jlongstreeta', 'Jackie', 'Longstreet', '2005-08-25', 'jT3$*Hy2!S%{D=', '09/03/2000');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (12, 'msimperb', 'Mahalia', 'Simper', '2004-03-12', 'yU5)o*fQj', '04/26/2000');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (13, 'tkilminsterc', 'Tristam', 'Kilminster', '1981-07-02', 'zE0$eqwG)00f', '12/05/2004');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (14, 'thunstond', 'Tripp', 'Hunston', '1985-04-26', 'yP7&E!r#}(pX{==k', '06/23/2009');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (15, 'clubbocke', 'Cindi', 'Lubbock', '1998-01-08', 'xJ7!M3IR40\d8', '07/07/2000');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (16, 'ncumbridgef', 'Norry', 'Cumbridge', '1990-04-25', 'uY6,vOJS3j25E', '08/01/2007');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (17, 'rliasg', 'Rodolfo', 'Lias', '1987-04-26', 'dE4{hu_APs', '04/04/2004');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (18, 'rgrimmetth', 'Rosemary', 'Grimmett', '1994-05-01', 'yB7*{WjW', '07/02/2002');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (19, 'jcoldmani', 'Junie', 'Coldman', '1982-05-20', 'jH0+x*=CrqZo', '04/30/2008');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (20, 'dkerslakej', 'Duane', 'Kerslake', '2008-02-07', 'tQ4`G!''.wfH*', '06/24/2008');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (21, 'satwaterk', 'Shepard', 'Atwater', '2007-11-18', 'rC8#{x#1AKL', '11/30/2006');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (22, 'cdorricottl', 'Christoforo', 'Dorricott', '1984-01-04', 'qX3''_NsI(2_', '07/29/2000');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (23, 'uroukem', 'Uriah', 'Rouke', '1982-10-21', 'zI4\Vs5\)kVA', '12/02/2000');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (24, 'thartwrightn', 'Tedra', 'Hartwright', '2003-08-01', 'mU0}Sc*UU', '02/07/2001');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (25, 'slethbrigo', 'Shoshana', 'Lethbrig', '1992-04-24', 'kV4".XD(J', '03/01/2002');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (26, 'bbaalhamp', 'Brietta', 'Baalham', '1986-07-29', 'aQ9.t&MlpF5', '01/20/2004');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (27, 'eduggenq', 'Emile', 'Duggen', '1983-03-06', 'nC7(qunc<AFvV0|Y', '12/27/2005');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (28, 'ddepaeper', 'Dulci', 'De Paepe', '1988-10-08', 'vW9%=gZ\}', '02/28/2007');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (29, 'lszymaniaks', 'Lucille', 'Szymaniak', '1983-01-23', 'yZ6)wHC.XP', '06/03/2005');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (30, 'bpescudt', 'Boyd', 'Pescud', '1980-10-21', 'bZ7##{GP', '08/04/2009');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (31, 'nmaffiau', 'Nataline', 'Maffia', '1980-12-06', 'qA0}k%)n', '09/24/2004');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (32, 'gturbernv', 'Gilligan', 'Turbern', '2006-02-11', 'vL6+T+OW', '07/01/2001');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (33, 'jmithamw', 'Jacki', 'Mitham', '1983-08-17', 'hW5''HSUgkf23)6', '12/02/2002');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (34, 'lguagex', 'Leigha', 'Guage', '2000-12-04', 'yR1\.hRd(', '11/01/2001');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (35, 'ccornelsy', 'Christopher', 'Cornels', '1998-06-20', 'dO1|CjCiN', '09/24/2009');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (36, 'zrosenz', 'Zilvia', 'Rosen', '1985-12-28', 'lP1(H&?r+GZK,tk!', '11/30/2004');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (37, 'mpanichelli10', 'Maybelle', 'Panichelli', '1999-05-13', 'fX4%D=Hgf@/6', '11/18/2004');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (38, 'wshirlaw11', 'Westley', 'Shirlaw', '1994-10-27', 'yW8#4a,Kg_', '01/19/2002');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (39, 'acollerd12', 'Alis', 'Collerd', '1999-04-17', 'pR4>Z!&EBSC9%v', '01/25/2003');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (40, 'fcussins13', 'Flossy', 'Cussins', '2007-09-17', 'pQ4>@WTq`9Jo9Tq.', '02/07/2008');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (41, 'mtriebner14', 'Melloney', 'Triebner', '2009-01-25', 'zF6~p%K1s,}?xx/3', '12/05/2008');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (42, 'mstickford15', 'May', 'Stickford', '2003-07-05', 'gJ1}Szhv9!', '02/07/2009');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (43, 'sflanigan16', 'Sheilah', 'Flanigan', '2005-08-02', 'fW4\?}9a4dWFc', '10/08/2003');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (44, 'edelacourt17', 'Elias', 'Delacourt', '2006-06-01', 'zK4`OUuQj', '02/07/2000');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (45, 'kshanklin18', 'Kayle', 'Shanklin', '1987-02-23', 'hI3`tm$ZomHHC', '03/05/2003');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (46, 'msellen19', 'Marty', 'Sellen', '1995-12-19', 'yK1|$yp%Q', '09/28/2008');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (47, 'jkopfen1a', 'Jordon', 'Kopfen', '2005-03-27', 'aW3|xo$IuaWzdz.''', '11/26/2004');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (48, 'kmartell1b', 'Kessia', 'Martell', '2001-10-03', 'sW9,lvF>I,_>n\', '05/29/2000');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (49, 'lslopier1c', 'Lezlie', 'Slopier', '1986-07-30', 'rN4!`Nlp|', '10/29/2003');
insert into Users (UserID, Username, FirstName , LastName, DateOfBirth, Password, DateAdded) values (50, 'eomolan1d', 'Eustace', 'O'' Molan', '1981-02-04', 'sX6''Rx\v', '08/10/2000');

insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (1, 16, 1, true, '03/20/2009');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (2, 6, 18, true, '02/13/2000');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (3, 12, 5, false, '08/29/2004');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (4, 10, 3, false, '01/14/2008');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (5, 17, 15, true, '12/12/2008');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (6, 20, 4, false, '10/04/2002');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (7, 20, 11, true, '08/04/2008');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (8, 3, 9, false, '01/07/2000');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (9, 7, 8, true, '04/23/2008');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (10, 4, 15, true, '10/31/2008');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (11, 1, 18, false, '06/01/2008');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (12, 6, 19, false, '11/29/2007');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (13, 1, 10, true, '10/19/2002');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (14, 14, 13, false, '11/12/2006');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (15, 7, 16, false, '04/24/2006');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (16, 9, 8, false, '11/13/2003');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (17, 4, 12, false, '12/20/2008');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (18, 2, 11, true, '05/10/2005');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (19, 4, 7, false, '11/06/2002');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (20, 6, 3, false, '12/11/2003');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (21, 6, 17, false, '04/30/2006');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (22, 6, 8, false, '10/13/2002');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (23, 6, 12, false, '10/05/2004');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (24, 15, 13, true, '10/13/2007');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (25, 14, 5, true, '05/21/2007');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (26, 9, 12, false, '04/29/2005');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (27, 17, 17, false, '06/10/2008');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (28, 2, 1, false, '08/28/2001');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (29, 7, 10, false, '04/30/2002');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (30, 4, 16, true, '03/27/2007');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (31, 5, 18, false, '06/29/2006');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (32, 19, 6, false, '03/21/2003');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (33, 2, 16, true, '10/29/2001');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (34, 20, 12, false, '07/23/2007');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (35, 16, 10, true, '01/14/2002');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (36, 13, 19, false, '05/08/2008');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (37, 5, 10, false, '02/17/2000');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (38, 12, 17, true, '01/31/2009');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (39, 7, 1, false, '10/15/2007');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (40, 13, 1, true, '10/31/2003');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (41, 19, 9, false, '03/12/2005');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (42, 19, 11, true, '07/09/2003');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (43, 4, 5, true, '08/26/2005');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (44, 10, 7, true, '05/25/2004');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (45, 3, 6, false, '12/10/2009');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (46, 13, 17, false, '06/01/2009');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (47, 19, 18, false, '05/31/2005');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (48, 17, 16, true, '10/21/2002');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (49, 3, 16, false, '04/07/2009');
insert into Friends (FriendID, FriendWhoAdded, FriendBeingAdded, IsAccepted, DateAdded) values (50, 8, 13, true, '02/18/2009');


insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (1, 'Toughjoyfax', 1, '03/22/2008');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (2, 'Y-find', 2, '05/19/2009');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (3, 'Ventosanzap', 3, '12/22/2003');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (4, 'Job', 4, '11/30/2005');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (5, 'Home Ing', 5, '07/14/2007');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (6, 'Ronstring', 6, '09/15/2006');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (7, 'Opela', 7, '04/29/2005');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (8, 'Temp', 8, '08/15/2003');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (9, 'Stim', 9, '12/29/2008');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (10, 'Cardify', 10, '07/04/2002');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (11, 'Fintone', 11, '06/19/2000');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (12, 'Redhold', 12, '03/25/2002');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (13, 'Treeflex', 13, '09/06/2009');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (14, 'Domainer', 14, '09/07/2005');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (15, 'Opela', 15, '04/02/2000');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (16, 'Rank', 16, '07/31/2008');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (17, 'Cardguard', 17, '07/14/2005');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (18, 'Y-Solowarm', 18, '02/20/2002');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (19, 'Quo Lux', 19, '01/12/2008');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (20, 'Toughjoyfax', 20, '11/30/2001');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (21, 'Bamity', 21, '06/27/2004');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (22, 'Flowdesk', 22, '02/19/2005');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (23, 'Biodex', 23, '06/17/2008');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (24, 'Mat Lam Tam', 24, '07/25/2003');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (25, 'Holdlamis', 25, '05/10/2007');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (26, 'Bigtax', 26, '07/16/2002');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (27, 'Keylex', 27, '01/11/2000');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (28, 'Alphazap', 28, '07/26/2000');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (29, 'Span', 29, '03/26/2005');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (30, 'Kanlam', 30, '12/31/2003');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (31, 'Bytecard', 31, '08/15/2008');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (32, 'Lotlux', 32, '06/05/2004');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (33, 'Namfix', 33, '12/13/2005');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (34, 'Stim', 34, '04/07/2008');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (35, 'Toughjoyfax', 35, '12/30/2007');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (36, 'Tin', 36, '11/17/2001');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (37, 'Tres-Zap', 37, '03/28/2003');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (38, 'Lotstring', 38, '09/26/2008');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (39, 'Bitwolf', 39, '06/04/2004');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (40, 'Quo Lux', 40, '08/10/2004');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (41, 'Holdlamis', 41, '07/11/2007');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (42, 'Voltsillam', 42, '12/29/2007');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (43, 'Zontrax', 43, '03/01/2005');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (44, 'Bytecard', 44, '03/16/2007');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (45, 'Redhold', 45, '08/25/2005');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (46, 'It', 46, '10/31/2004');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (47, 'Konklux', 47, '03/14/2002');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (48, 'Flexidy', 48, '11/21/2002');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (49, 'Sonsing', 49, '09/28/2009');
insert into Groups (GroupID, GroupName, CreatedBy, DateAdded) values (50, 'Bytecard', 50, '09/12/2009');


insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (1, 'Synergized', 1, true, false, 1, '01/17/2005');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (2, 'internet solution', 2, false, true, 2, '10/22/2003');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (3, 'systemic', 3, false, false, 3, '06/03/2005');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (4, 'Grass-roots', 4, false, true, 4, '04/12/2008');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (5, 'data-warehouse', 5, false, false, 5, '05/12/2001');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (6, 'ability', 6, false, false, 6, '05/13/2001');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (7, 'Reduced', 7, true, false, 7, '09/23/2005');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (8, 'cohesive', 8, false, false, 8, '01/02/2003');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (9, 'Cloned', 9, true, true, 9, '12/21/2007');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (10, 'Decentralized', 10, false, true, 10, '04/30/2007');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (11, 'Seamless', 11, true, true, 11, '05/11/2005');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (12, 'process improvement', 12, true, true, 12, '06/23/2006');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (13, 'regional', 13, true, true, 13, '11/24/2001');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (14, 'synergy', 14, false, false, 14, '01/19/2003');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (15, 'demand-driven', 15, false, false, 15, '04/24/2006');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (16, 'Compatible', 16, true, true, 16, '12/14/2007');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (17, 'help-desk', 17, false, false, 17, '06/02/2007');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (18, 'core', 18, false, true, 18, '12/27/2009');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (19, 'motivating', 19, false, true, 19, '02/04/2006');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (20, 'Multi-lateral', 20, true, true, 20, '09/03/2000');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (21, 'encryption', 21, true, true, 21, '07/03/2005');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (22, 'Upgradable', 22, false, true, 22, '02/06/2008');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (23, 'modular', 23, false, false, 23, '11/21/2008');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (24, 'implementation', 24, true, false, 24, '01/28/2001');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (25, 'tangible', 25, false, false, 25, '12/14/2005');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (26, 'application', 26, true, false, 26, '01/28/2008');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (27, 'bandwidth-monitored', 27, true, true, 27, '12/31/2008');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (28, 'Re-contextualized', 28, true, true, 28, '02/14/2003');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (29, 'time-frame', 29, false, false, 29, '10/06/2003');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (30, 'Graphic Interface', 30, false, false, 30, '07/31/2001');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (31, 'leading edge', 31, true, true, 31, '10/20/2004');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (32, 'concept', 32, true, false, 32, '09/24/2003');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (33, 'maximized', 33, false, false, 33, '05/02/2008');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (34, 'incremental', 34, false, true, 34, '03/21/2007');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (35, 'protocol', 35, true, true, 35, '06/17/2003');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (36, 'artificial intelligence', 36, true, true, 36, '02/06/2007');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (37, 'asymmetric', 37, false, false, 37, '08/10/2008');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (38, 'zero administration', 38, false, true, 38, '11/18/2003');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (39, 'contextually-based', 39, true, true, 39, '07/25/2004');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (40, 'Grass-roots', 40, false, true, 40, '04/21/2009');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (41, 'process improvement', 41, true, true, 41, '07/21/2009');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (42, 'utilisation', 42, false, true, 42, '05/29/2000');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (43, 'Right-sized', 43, true, true, 43, '01/21/2004');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (44, 'leading edge', 44, true, true, 44, '12/14/2006');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (45, 'transitional', 45, true, true, 45, '01/02/2008');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (46, 'solution', 46, true, false, 46, '10/01/2008');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (47, 'Self-enabling', 47, false, true, 47, '09/27/2004');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (48, 'intranet', 48, true, false, 48, '11/18/2009');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (49, 'support', 49, false, false, 49, '11/23/2002');
insert into Posts (PostID, PostDescription, PostedBy, IsPublic, IsOnlyForFriends, GroupID, DatePosted) values (50, 'Exclusive', 50, true, false, 50, '04/04/2009');


insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (1, 1, 1, false, '10/20/2007');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (2, 2, 2, false, '11/20/2005');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (3, 3, 3, false, '07/24/2002');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (4, 4, 4, false, '05/14/2007');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (5, 5, 5, false, '09/19/2009');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (6, 6, 6, true, '05/17/2001');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (7, 7, 7, true, '02/25/2001');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (8, 8, 8, false, '05/24/2005');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (9, 9, 9, false, '11/12/2000');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (10, 10, 10, false, '10/24/2008');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (11, 11, 11, false, '03/23/2004');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (12, 12, 12, false, '08/26/2002');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (13, 13, 13, true, '10/04/2007');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (14, 14, 14, false, '02/01/2008');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (15, 15, 15, false, '02/20/2007');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (16, 16, 16, false, '01/14/2003');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (17, 17, 17, true, '01/28/2002');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (18, 18, 18, false, '03/16/2007');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (19, 19, 19, false, '11/09/2002');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (20, 20, 20, false, '11/11/2001');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (21, 21, 21, false, '11/24/2002');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (22, 22, 22, true, '04/06/2000');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (23, 23, 23, false, '11/24/2000');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (24, 24, 24, false, '09/04/2008');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (25, 25, 25, true, '01/14/2003');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (26, 26, 26, false, '04/20/2003');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (27, 27, 27, true, '11/12/2006');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (28, 28, 28, true, '09/01/2009');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (29, 29, 29, true, '06/09/2009');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (30, 30, 30, true, '07/11/2006');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (31, 31, 31, false, '06/10/2000');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (32, 32, 32, true, '11/15/2002');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (33, 33, 33, true, '03/15/2003');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (34, 34, 34, false, '08/31/2008');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (35, 35, 35, false, '07/23/2005');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (36, 36, 36, true, '08/14/2007');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (37, 37, 37, true, '06/03/2004');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (38, 38, 38, true, '12/29/2004');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (39, 39, 39, false, '10/11/2004');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (40, 40, 40, true, '07/31/2009');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (41, 41, 41, false, '05/28/2005');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (42, 42, 42, false, '07/11/2003');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (43, 43, 43, false, '10/24/2000');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (44, 44, 44, true, '03/13/2008');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (45, 45, 45, false, '12/16/2007');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (46, 46, 46, false, '09/14/2005');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (47, 47, 47, true, '07/05/2002');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (48, 48, 48, true, '11/28/2006');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (49, 49, 49, false, '02/22/2001');
insert into GroupMembershipRequests (GroupMemberShipRequestsID, GroupID, GroupMemberUserID, IsGroupMemberShipAccepted, DateAccepted) values (50, 50, 50, false, '08/13/2001');